import { QuizQuestion } from '../types';

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    topicId: 1,
    topicTitle: 'Topic 1: Fundamentals of Java',
    question: 'What is the primary role of the Java Virtual Machine (JVM) in the "Write Once, Run Anywhere" philosophy?',
    options: [
      'Translating .java source code directly to physical hardware without compilation',
      'Executing compiled Bytecode (.class) instructions into machine code for the target operating system',
      'Checking algorithm logic errors before the user compiles the code',
      'Automatically refactoring and editing program source files'
    ],
    correctAnswerIndex: 1,
    explanation: 'The JVM is responsible for taking compiled Java Bytecode (.class files) generated by the javac compiler and translating it into native machine code instructions for the host platform.',
    difficulty: 'Easy'
  },
  {
    id: 2,
    topicId: 1,
    topicTitle: 'Topic 1: Fundamental of Algorithms',
    question: 'In standard flowchart diagrams, which symbol is used to represent a Decision or Condition?',
    options: [
      'Rectangle (Process)',
      'Oval (Terminal)',
      'Diamond / Rhombus (Decision)',
      'Parallelogram (Input/Output)'
    ],
    correctAnswerIndex: 2,
    explanation: 'A Diamond (Rhombus) symbol represents a conditional Decision branch with two or more outgoing flow paths such as Yes / No or True / False.',
    difficulty: 'Easy'
  },
  {
    id: 3,
    topicId: 2,
    topicTitle: 'Topic 2: Problem Solving & Modularization',
    question: 'What is the key advantage of applying Modularization in software development?',
    options: [
      'Making source code files larger and harder for hackers to read',
      'Enhancing code reusability and simplifying debugging and unit testing',
      'Eliminating the need to declare variables in program memory',
      'Allowing programs to run without utilizing any RAM memory'
    ],
    correctAnswerIndex: 1,
    explanation: 'Modularization breaks complex problems into smaller, independent sub-routines. This improves code readability, simplifies debugging, and maximizes reusability.',
    difficulty: 'Easy'
  },
  {
    id: 4,
    topicId: 3,
    topicTitle: 'Topic 3: Structured Programming',
    question: 'What is the printed output of the following Java code snippet?',
    codeSnippet: `int x = 7;
int y = 2;
double result = x / y;
System.out.println(result);`,
    options: [
      '3.5',
      '3.0',
      '4.0',
      'Compilation Error (Syntax Error)'
    ],
    correctAnswerIndex: 1,
    explanation: 'Because both x and y are integer types, integer division occurs first: 7 / 2 = 3. That integer value 3 is then widened to double, yielding 3.0.',
    difficulty: 'Medium'
  },
  {
    id: 5,
    topicId: 3,
    topicTitle: 'Topic 3: Structured Programming',
    question: 'Which of the following is a valid Java identifier according to standard language naming rules?',
    options: [
      '1stStudentScore',
      'total_Score$',
      'class',
      'item-price'
    ],
    correctAnswerIndex: 1,
    explanation: 'Java identifiers can contain letters, numbers, underscores (_), and dollar signs ($). They cannot begin with numbers, cannot be reserved keywords ("class"), and cannot include hyphens (-).',
    difficulty: 'Medium'
  },
  {
    id: 6,
    topicId: 4,
    topicTitle: 'Topic 4: Selection & Loops',
    question: 'How many times will "BolehCode" be printed in the following while loop?',
    codeSnippet: `int count = 3;
while (count > 0) {
    System.out.println("BolehCode");
    count--;
}`,
    options: [
      '2 times',
      '3 times',
      '4 times',
      'Infinite loop (never terminates)'
    ],
    correctAnswerIndex: 1,
    explanation: 'Iteration 1: count = 3 (prints, count becomes 2). Iteration 2: count = 2 (prints, count becomes 1). Iteration 3: count = 1 (prints, count becomes 0). The condition 0 > 0 evaluates to false. Total prints: 3 times.',
    difficulty: 'Easy'
  },
  {
    id: 7,
    topicId: 4,
    topicTitle: 'Topic 4: Selection & Loops',
    question: 'What is the fundamental difference between a do-while loop and a standard while loop?',
    options: [
      'A do-while loop never requires a termination condition',
      'A do-while loop always executes its body at least once before testing the condition',
      'A do-while loop can only evaluate char variables',
      'A do-while loop executes significantly faster than a for loop'
    ],
    correctAnswerIndex: 1,
    explanation: 'Because the condition is evaluated at the end of the iteration (post-test loop), statements inside a do-while body are guaranteed to execute at least once.',
    difficulty: 'Easy'
  },
  {
    id: 8,
    topicId: 5,
    topicTitle: 'Topic 5: Array & String Manipulation',
    question: 'Given the array: `int[] list = {10, 20, 30, 40};`. What happens if the program accesses `list[4]`?',
    options: [
      'Returns 0',
      'Returns 40',
      'Throws a runtime `ArrayIndexOutOfBoundsException`',
      'Dynamically appends a new element slot to the array'
    ],
    correctAnswerIndex: 2,
    explanation: 'An array of size 4 is indexed from 0 to 3 (list[0] through list[3]). Accessing index 4 attempts to read beyond the allocated boundary, throwing an ArrayIndexOutOfBoundsException.',
    difficulty: 'Medium'
  },
  {
    id: 9,
    topicId: 5,
    topicTitle: 'Topic 5: String Manipulation',
    question: 'What is the output of the following String comparison code in Java?',
    codeSnippet: `String a = new String("Java");
String b = new String("Java");
System.out.println(a == b);
System.out.println(a.equals(b));`,
    options: [
      'true followed by true',
      'false followed by true',
      'true followed by false',
      'false followed by false'
    ],
    correctAnswerIndex: 1,
    explanation: 'The `==` operator compares memory reference addresses (two separate instances created via `new` reside in different memory locations, returning false). The `.equals()` method compares the underlying character values, returning true.',
    difficulty: 'Medium'
  },
  {
    id: 10,
    topicId: 6,
    topicTitle: 'Topic 6: Function Method',
    question: 'What does the `static` keyword specify before a method return type such as `public static void calculate()`?',
    options: [
      'The method value can never be altered',
      'The method belongs to the class itself and can be called without instantiating an object',
      'The method can only be invoked once upon startup',
      'The method runs asynchronously in a worker thread'
    ],
    correctAnswerIndex: 1,
    explanation: 'The `static` modifier specifies that a member belongs to the class itself (class-level), rather than to individual instances of the class.',
    difficulty: 'Medium'
  },
  {
    id: 11,
    topicId: 6,
    topicTitle: 'Topic 6: Method Overloading',
    question: 'Which of the following method pairs demonstrates valid Method Overloading in Java?',
    options: [
      'void calc(int a) and int calc(int a)',
      'void print(int a) and void print(String s)',
      'public void run() and private void run()',
      'void calc(int x, int y) and void calc(int a, int b)'
    ],
    correctAnswerIndex: 1,
    explanation: 'Method Overloading requires the exact same method name with a different parameter list (differing in quantity or parameter types). Changing only the return type or access modifier is invalid.',
    difficulty: 'Hard'
  },
  {
    id: 12,
    topicId: 7,
    topicTitle: 'Topic 7: GUI & Swing Components',
    question: 'In the javax.swing library, which component represents the primary top-level window featuring a title bar, minimize, and close controls?',
    options: [
      'JPanel',
      'JButton',
      'JFrame',
      'JLabel'
    ],
    correctAnswerIndex: 2,
    explanation: '`JFrame` is the top-level container that represents the primary desktop window with title bar borders and OS window controls.',
    difficulty: 'Easy'
  },
  {
    id: 13,
    topicId: 8,
    topicTitle: 'Topic 8: Text File Manipulation',
    question: 'What is the primary benefit of wrapping a `FileReader` with a `BufferedReader`?',
    options: [
      'BufferedReader allows reading images and binary multimedia',
      'BufferedReader provides an in-memory buffer for efficient batch I/O and provides the handy readLine() method',
      'BufferedReader eliminates the requirement to handle IOException',
      'BufferedReader automatically encrypts files on disk'
    ],
    correctAnswerIndex: 1,
    explanation: 'Without a buffer, every read request on FileReader invokes disk I/O. BufferedReader reads larger memory blocks into RAM and provides the convenient `.readLine()` helper.',
    difficulty: 'Medium'
  },
  {
    id: 14,
    topicId: 8,
    topicTitle: 'Topic 8: File Exceptions',
    question: 'Why must a `try-catch` block or `throws IOException` declaration be provided when handling text files in Java?',
    options: [
      'Because Java restricts external file operations by default',
      'Because IOException is a Checked Exception mandated by the compiler to prevent unhandled runtime file failures',
      'To allow opening text files inside word processors',
      'To reduce device battery consumption during runtime'
    ],
    correctAnswerIndex: 1,
    explanation: 'IOException is a Checked Exception in Java. The compiler enforces that developers either catch it via try-catch or declare it with `throws` to ensure software stability when files are missing or unreadable.',
    difficulty: 'Hard'
  }
];
